name: linearc_task_note
description: Helps you, take note of your tasks.



publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.0"
  flutter_app_name: ^0.1.0

  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "Taskr"

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"